<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.6</version>
        <relativePath/>
    </parent>

    <groupId>com.dayang</groupId>
    <artifactId>dayang-town</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>dayang-town</name>
    <description>dayang-town</description>

    <modules>
        <module>dayang-api</module>
        <module>dayang-common</module>
        <module>dayang-framework</module>
        <module>dayang-modules</module>
        <module>dayang-bootstrap</module>
    </modules>

    <properties>
        <java.version>17</java.version>
        <tomcat.version>10.1.50</tomcat.version>
        <jackson-bom.version>2.21.1</jackson-bom.version>
        <logback.version>1.5.25</logback.version>
        <assertj.version>3.27.7</assertj.version>
        <mysql.version>8.0.33</mysql.version>
        <mybatis.version>3.0.5</mybatis.version>
        <jwt.version>0.12.6</jwt.version>
        <protobuf.version>4.28.3</protobuf.version>
        <lang3.version>3.18.0</lang3.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.dayang</groupId>
                <artifactId>dayang-common</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>

            <dependency>
                <groupId>com.dayang</groupId>
                <artifactId>dayang-framework</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>

            <dependency>
                <groupId>com.google.protobuf</groupId>
                <artifactId>protobuf-java</artifactId>
                <version>${protobuf.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>${lang3.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>


    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
